"use client";

import type { Metadata } from "next";
import { useSession, signIn } from "next-auth/react";
import { useRouter, redirect, RedirectType } from "next/navigation";
import { useEffect } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("Auth Layout Called");
  return (
    <>
      <div className="flex flex-col md:flex-row flex-1 bg-blue-950">
        <main className="flex-1">{children}</main>
      </div>
    </>
  );
}
