import type { Metadata } from "next";
import Image from "next/image";

import Navbar from "@components/Navbars/NavbarHome";
import Footer from "@components/Footers/FooterHome";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <div className="flex flex-col md:flex-row flex-1">
        <main className="flex-1">{children}</main>
      </div>
      <Footer />
    </>
  );
}
