import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ToasterProvider from "@providers/ToasterProvider";
import { EventMessageProvider } from "@contexts/EventMessageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://localhost:7072/SFLHub.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <ToasterProvider />
        <EventMessageProvider>
          <div className="min-h-screen flex flex-col">{children}</div>
        </EventMessageProvider>
      </body>
    </html>
  );
}
